title: Devansh's Blog
description: A personal space where I pen down my thoughts on Cybersecurity, Psychology, Artificial Intelligence, Philosophy, and the list goes on . . .
description: “There is only one good, knowledge, and one evil, ignorance” – Socrates
author: Devansh Batham
avatar: /logo.png
email: devanshbatham009@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
google_analytics: G-NYBE15XXTP

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: 0xAsm0d3us
  card: summary
logo: logo.png
social:
  name: Devansh Batham
  links:
    - https://twitter.com/0xAsm0d3us
    - https://github.com/devanshbatham

lang: en